baseURL = "https://pawson.dev/"
languageCode = "en-us"
title = "Kent Pawson Portfolio Website"

[params]
summaryLength = 55

[menu]
    [[menu.nav]]
    name = "About"
    URL = "#about"
    weight = 1

    [[menu.nav]]
    name = "Experience"
    URL = "#experience"
    weight = 2

    [[menu.nav]]
    name = "Projects"
    URL = "#project"
    weight = 3

    [[menu.nav]]
    name = "Skills"
    URL = "#skill"
    weight = 4

    [[menu.nav]]
    name = "Blogs"
    URL = "#blog"
    weight = 5

    [[menu.nav]]
    name = "Contact"
    URL = "#contact"
    weight = 6

[params.social]
    github = "https://github.com/kp4ws"
    linkedin = "https://www.linkedin.com/in/kentpawson/"
    itchio = "https://kpaws-games.itch.io/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true